# make a symlink of this file in your home directory with
# ln -s ~/.config/.tmux.conf ~/.tmux.conf

# KEY BINDINGS
# vi-style navigation bindings for copy mode
set-window-option -g mode-keys vi

# v: starts selection in copy mode
bind-key -T copy-mode-vi v send -X begin-selection

# V: selects entire line in copy mode
bind-key -T copy-mode-vi V send -X select-line

# PLUGINS
# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'

# some sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# seamless navigation between vim and tmux
set -g @plugin 'christoomey/vim-tmux-navigator'

# convenient copy/paste bindings
# y: yanks selection
# prefix+y: copy command line
# Y: copy and paste to command line
# prefix+Y: copy cwd
set -g @plugin 'tmux-plugins/tmux-yank'

# handy predefined searches and regex search
# prefix+<c-f>: simple file search
# prefix+<c-g>: jumping over git status files (best used after git status command)
# prefix+<m-h>: jumping over SHA-1/SHA-256 hashes (best used after git log command)
# prefix+<c-u>: url search (http, ftp and git urls)
# prefix+<c-d>: number search (mnemonic d, as digit)
# prefix+<m-i>: ip address search
# previx+/: regex search
# n/N: next/previous match
set -g @plugin 'tmux-plugins/tmux-copycat'

# open selected files and URLs
# o: open file in default app/browser
# <c-o>: open file in default $EDITOR
set -g @plugin 'tmux-plugins/tmux-open'
set -g @open-editor-command '/opt/homebrew/bin/nvim' # set nvim as the editor

# saves and restores an entire session
# save: prefix+<c-s>; restore: prefix+<c-r>
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session' # include nvim sessions

# auto-save/restore sessions and auto-start tmux
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on' # auto-restore last saved session on tmux start

# seamless mouse scrolling in tmux
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g mouse on
set -g @mighty-scroll-interval 3
set -g @mighty-scroll-show-indicator on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
